name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  PROJECT_ID: liff-survey-app-20250809-282a6
  CLOUD_RUN_SERVICE: liff-survey-api
  CLOUD_RUN_REGION: asia-northeast1

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov httpx

    - name: Run tests
      run: |
        cd backend
        pytest tests/unit tests/integration --cov=. --cov-report=xml --ignore=tests/e2e

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./backend
        flags: backend

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        cd backend
        docker build -t gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }} .
        docker build -t gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:latest .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }}
        docker push gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
          --image gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }} \
          --platform managed \
          --region ${{ env.CLOUD_RUN_REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --max-instances 10
######################################################################
# Backend CI/CD workflow is disabled. All steps are commented out.    #
# To re-enable, uncomment the lines below.                            #
######################################################################
# name: Backend CI/CD
# 
# on:
#   push:
#     branches: [ main, develop ]
#     paths:
#       - 'backend/**'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - 'backend/**'
# 
# env:
#   PROJECT_ID: liff-survey-app-20250809-282a6
#   CLOUD_RUN_SERVICE: liff-survey-api
#   CLOUD_RUN_REGION: asia-northeast1
# 
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v4
# 
#     - name: Setup Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'
# 
#     - name: Install dependencies
#       run: |
#         cd backend
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#         pip install pytest pytest-cov httpx
# 
#     - name: Run tests
#       run: |
#         cd backend
#         pytest tests/unit tests/integration --cov=. --cov-report=xml --ignore=tests/e2e
# 
#     - name: Upload coverage reports
#       uses: codecov/codecov-action@v3
#       with:
#         directory: ./backend
#         flags: backend
# 
#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     
#     steps:
#     - uses: actions/checkout@v4
# 
#     - name: Authenticate to Google Cloud
#       uses: google-github-actions/auth@v2
#       with:
#         credentials_json: ${{ secrets.GCP_CREDENTIALS }}
# 
#     - name: Setup Google Cloud CLI
#       uses: google-github-actions/setup-gcloud@v2
# 
#     - name: Configure Docker for GCR
#       run: gcloud auth configure-docker
# 
#     - name: Build Docker image
#       run: |
#         cd backend
#         docker build -t gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }} .
#         docker build -t gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:latest .
# 
#     - name: Push Docker image
#       run: |
#         docker push gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }}
#         docker push gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:latest
# 
#     - name: Deploy to Cloud Run
#       run: |
#         gcloud run deploy ${{ env.CLOUD_RUN_SERVICE }} \
#           --image gcr.io/${{ env.PROJECT_ID }}/liff-survey-api:${{ github.sha }} \
#           --platform managed \
#           --region ${{ env.CLOUD_RUN_REGION }} \
#           --allow-unauthenticated \
#           --port 8080 \
#           --memory 512Mi \
#           --cpu 1 \
#           --max-instances 10
